# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-strict
"""Static declarations for the CinderX plugin framework."""

from .artifacts import (
    ArtifactBudgets,
    ArtifactIssue,
    ArtifactIssueCode,
    ArtifactVerificationResult,
    MAX_CLOSURE_EDGES,
    MAX_CLOSURE_NODES,
    MAX_DIAGNOSTIC_BYTES,
    MAX_EVIDENCE_PATH_BYTES,
    MAX_INSPECTED_FILE_RECORDS,
    MAX_RECORD_BYTES,
    MAX_REQUIREMENT_BYTES,
    verify_distribution_closure,
    verify_distribution_closures,
)
from .discovery import (
    DiscoveryIssue,
    DiscoveryIssueCode,
    MANIFEST_FILENAME,
    PluginDiscoveryResult,
    discover,
    normalize_distribution_name,
)
from .manifest import (
    CURRENT_SPI_VERSION,
    MAX_ENTRIES_PER_SECTION,
    MAX_IDENTIFIER_BYTES,
    MAX_MANIFEST_BYTES,
    MAX_PROVIDE_ENTRIES,
    MAX_TARGET_CAPABILITIES,
    ManifestIssue,
    ManifestIssueCode,
    ManifestValidationResult,
    PluginAdapter,
    PluginManifest,
    PluginProvides,
    RuntimeABI,
    parse_manifest,
    validate_manifest,
)
from .negotiation import (
    MAX_NEGOTIATION_DETAIL_CHARS,
    MAX_NEGOTIATION_DETAIL_VALUES,
    NegotiationIssue,
    NegotiationReason,
    PluginNegotiationResult,
    RuntimeFingerprint,
    negotiate,
)

__all__ = [
    "ArtifactBudgets",
    "ArtifactIssue",
    "ArtifactIssueCode",
    "ArtifactVerificationResult",
    "CURRENT_SPI_VERSION",
    "DiscoveryIssue",
    "DiscoveryIssueCode",
    "MANIFEST_FILENAME",
    "MAX_CLOSURE_EDGES",
    "MAX_CLOSURE_NODES",
    "MAX_DIAGNOSTIC_BYTES",
    "MAX_ENTRIES_PER_SECTION",
    "MAX_EVIDENCE_PATH_BYTES",
    "MAX_IDENTIFIER_BYTES",
    "MAX_INSPECTED_FILE_RECORDS",
    "MAX_RECORD_BYTES",
    "MAX_REQUIREMENT_BYTES",
    "MAX_MANIFEST_BYTES",
    "MAX_NEGOTIATION_DETAIL_CHARS",
    "MAX_NEGOTIATION_DETAIL_VALUES",
    "MAX_PROVIDE_ENTRIES",
    "MAX_TARGET_CAPABILITIES",
    "ManifestIssue",
    "ManifestIssueCode",
    "ManifestValidationResult",
    "NegotiationIssue",
    "NegotiationReason",
    "PluginAdapter",
    "PluginDiscoveryResult",
    "PluginManifest",
    "PluginNegotiationResult",
    "PluginProvides",
    "RuntimeABI",
    "RuntimeFingerprint",
    "discover",
    "negotiate",
    "normalize_distribution_name",
    "parse_manifest",
    "validate_manifest",
    "verify_distribution_closure",
    "verify_distribution_closures",
]
