# Copyright (c) Meta Platforms, Inc. and affiliates.
"""Trigger-proof test drivers for the CPython 3.11 JIT gates.

Eight drivers defined by the development plan (docs/cp311-jit-dev-plan.md,
MR-01).  Each drives a workload in a child interpreter, collects the unified
trigger-proof report at child exit, fills in the harness-owned fields, and
judges the result against explicit expectations.  The judging contract is
what makes these problem-front-loading rather than smoke tests:

  * an expected trigger that did not fire is a failure, never a pass;
  * a worker that dies or produces no report is a failure, never a skip;
  * environment configuration is asserted inside the child, not assumed.

The default expectations track the current stage: off/observe workloads pin
the execution gate, while cold/warm/auto/shadow workloads require successful
shadow compilation and prove that no generated bytes are installed or run.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

from ci_pipeline.jit311 import report as _report

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
LIBTEST_TARGET_MANIFEST = (
    REPO_ROOT / "ci_pipeline" / "jit311" / "data" / "libtest_target_modules.txt"
)
PYPERF_BENCHMARKS = (
    REPO_ROOT / "ci_pipeline" / "jit311" / "data" / "pyperf_benchmarks.txt"
)

# Runs inside every child before the payload: activate the evaluator and
# arrange for the trigger-proof report to be written at exit.
CHILD_PREAMBLE = """\
import atexit, json, os, sys
sys.path.insert(0, os.environ["JIT311_REPO_ROOT"])
import _cinderx
import cinderx
cinderx.init()
_cinderx.install_frame_evaluator()

from ci_pipeline.jit311 import report as _jit311_report

_jit311_target_modules_attempted = 0

def _jit311_emit():
    installed = _cinderx.is_frame_evaluator_installed()
    # Logical lists answer "would a call enter machine code" -- read them
    # while the evaluator is still installed (atexit, before finalize).
    try:
        import cinderjit as _cinderjit_module
        from cinderjit import get_compiled_functions
        _live_at_exit = len(get_compiled_functions())
        # The logical count above answers "would a call enter machine
        # code".  A function that temporarily fell back -- its defaults
        # changed, say -- leaves that list while its artifact and code
        # buffer are still resident, so the physical count is reported
        # next to it rather than folded into it.
        _resident = getattr(
            _cinderjit_module, "_get_resident_compiled_functions", None
        )
        # An integer straight from the runtime; coercing a missing answer to
        # zero here would reintroduce the false negative this measures.
        _resident_at_exit = _resident() if _resident is not None else None
    except ImportError:
        _live_at_exit = 0
        _resident_at_exit = 0
    # Freeze scheduling before taking the multi-source snapshot.  Otherwise
    # report helper frames can themselves cross a low threshold between the
    # observe and trigger reads and make an internally inconsistent report.
    if installed:
        _cinderx.remove_frame_evaluator()
    snap = _jit311_report.snapshot()
    # snapshot() derives machine_code_installed from the same logical list
    # the removal above has just emptied; the pre-removal reading is the
    # truthful one.
    snap["machine_code_installed"] = _live_at_exit
    snap["evaluator_installed"] = installed
    snap["target_modules_attempted"] = _jit311_target_modules_attempted
    snap["live_compiled_functions_at_exit"] = _live_at_exit
    snap["resident_compiled_functions_at_exit"] = _resident_at_exit
    with open(os.environ["JIT311_REPORT_PATH"], "w") as fp:
        json.dump(snap, fp)

atexit.register(_jit311_emit)
"""

Judge = Callable[[dict], list[str]]


@dataclass
class RunResult:
    name: str
    ok: bool
    errors: list[str]
    report: dict | None
    returncode: int

    def summary(self) -> str:
        state = "ok" if self.ok else "FAIL"
        lines = [f"runner {self.name}: {state} (rc={self.returncode})"]
        lines += [f"  - {err}" for err in self.errors]
        return "\n".join(lines)


@dataclass
class RunnerSpec:
    name: str
    payload: str
    env: dict[str, str] = field(default_factory=dict)
    judges: list[Judge] = field(default_factory=list)
    # Expected-rejection specs (an unshipped mode) produce no report.
    expect_report: bool = True
    # Environment variables the child must observe with exactly these
    # values; asserted inside the child so a lost variable turns red.
    asserted_env: dict[str, str] = field(default_factory=dict)
    expect_returncode: int = 0
    # For expected-rejection specs: the child's stderr must contain this
    # substring, so an unrelated failure with the same exit code cannot
    # impersonate the pinned rejection.
    expect_stderr_contains: str | None = None
    timeout: int = 300
    target_modules_attempted: int = 0


def _env_assertions(asserted_env: dict[str, str]) -> str:
    lines = []
    for key, value in asserted_env.items():
        lines.append(
            f"assert os.environ.get({key!r}) == {value!r}, "
            f"('config not effective', {key!r}, os.environ.get({key!r}))"
        )
    return "\n".join(lines) + ("\n" if lines else "")


def run(spec: RunnerSpec, python: str | None = None) -> RunResult:
    """Run one workload child and judge its trigger-proof report."""
    python = python or sys.executable
    errors: list[str] = []
    with tempfile.TemporaryDirectory(prefix="jit311-") as tmp:
        report_path = os.path.join(tmp, "report.json")
        # Inherited CinderX / PYTHONJIT configuration would silently change
        # what every driver measures; a child sees only what its spec sets.
        env = {
            key: value
            for key, value in os.environ.items()
            if not key.startswith(("PYTHONJIT", "CINDERX_", "PARALLEL_GC_"))
        }
        env.update(spec.env)
        env["JIT311_REPORT_PATH"] = report_path
        env["JIT311_REPO_ROOT"] = str(REPO_ROOT)
        source = CHILD_PREAMBLE + _env_assertions(spec.asserted_env)
        source += spec.payload
        try:
            proc = subprocess.run(
                [python, "-c", source],
                env=env,
                capture_output=True,
                timeout=spec.timeout,
            )
            returncode = proc.returncode
        except subprocess.TimeoutExpired:
            return RunResult(spec.name, False, ["worker timeout"], None, -1)

        stderr_text = proc.stderr.decode(errors="replace")
        if returncode != spec.expect_returncode:
            errors.append(
                f"worker exited {returncode}, expected "
                f"{spec.expect_returncode}: {stderr_text[-400:]}"
            )
        if (
            spec.expect_stderr_contains is not None
            and spec.expect_stderr_contains not in stderr_text
        ):
            errors.append(
                "expected rejection marker "
                f"{spec.expect_stderr_contains!r} not found in stderr: "
                f"{stderr_text[-400:]}"
            )
        if not spec.expect_report:
            if os.path.exists(report_path):
                errors.append(
                    "expected-rejection spec produced a report; the payload "
                    "ran past the pinned rejection point"
                )
            return RunResult(spec.name, not errors, errors, None, returncode)
        if not os.path.exists(report_path):
            errors.append("worker produced no report (counts as a crash)")
            return RunResult(spec.name, False, errors, None, returncode)

        with open(report_path, encoding="utf8") as fp:
            snap = json.load(fp)
        snap["worker_crashes"] = 1 if returncode != 0 else 0
        errors.extend(
            f"report schema: {error}"
            for error in _validate_report_schema(snap)
        )
        for judge in spec.judges:
            errors.extend(judge(snap))
        return RunResult(spec.name, not errors, errors, snap, returncode)


# --------------------------------------------------------------------------
# Judges

def expect(field_name: str, op: str, value: int) -> Judge:
    """Field comparison judge: op is one of ==, >, >=."""

    def judge(snap: dict) -> list[str]:
        actual = snap.get(field_name)
        checks = {
            "==": actual == value,
            ">": isinstance(actual, int) and actual > value,
            ">=": isinstance(actual, int) and actual >= value,
        }
        if not checks[op]:
            return [f"expected {field_name} {op} {value}, got {actual!r}"]
        return []

    return judge


def _validate_report_schema(snap: dict) -> list[str]:
    # Import lazily so importing this driver remains side-effect free in the
    # parent process.
    from ci_pipeline.jit311.report import validate_schema

    return validate_schema(snap)


def requests_accounted() -> Judge:
    """Every recorded request must be either compiled or stably refused."""

    def judge(snap: dict) -> list[str]:
        requested = snap.get("compile_requests")
        accounted = snap.get("compile_success", 0) + snap.get(
            "compile_rejected", 0
        )
        if requested != accounted:
            return [
                "compile requests are not fully accounted: "
                f"requests={requested!r}, success+rejected={accounted!r}"
            ]
        return []

    return judge


def canary_requests_accounted() -> Judge:
    """Canary answers a request by installing machine code, so the ledger
    closes through compile_installed rather than the shadow counter."""

    def judge(snap: dict) -> list[str]:
        requested = snap.get("compile_requests")
        accounted = snap.get("compile_installed", 0) + snap.get(
            "compile_rejected", 0
        )
        if requested != accounted:
            return [
                "compile requests are not fully accounted: "
                f"requests={requested!r}, installed+rejected={accounted!r}"
            ]
        return []

    return judge


def organic_deopts_bounded_by_entries() -> Judge:
    """A driver whose work scales with its input (the pyperformance driver
    runs one subprocess per benchmark and parses every report) compiles a
    workload-dependent slice of the standard library, and the exception
    (MR-08) and attribute-cache (MR-09) surfaces deopt organically inside
    it.  An exact pin would track the benchmark list rather than the JIT;
    what must hold is that deopts never outrun entries -- the deopt-storm
    guard the worker side applies."""

    def judge(snap: dict) -> list[str]:
        deopts = snap.get("organic_deopt_hits")
        entries = snap.get("machine_code_entries")
        if not isinstance(deopts, int) or not isinstance(entries, int):
            return [
                "organic_deopt_hits / machine_code_entries missing: "
                f"{deopts!r} / {entries!r}"
            ]
        if deopts >= entries:
            return [
                "organic deopts reached machine-code entries (deopt storm): "
                f"{deopts} >= {entries}"
            ]
        return []

    return judge


def evaluator_is_installed(snap: dict) -> list[str]:
    if snap.get("evaluator_installed") is not True:
        return [
            "expected evaluator_installed is True, got "
            f"{snap.get('evaluator_installed')!r}"
        ]
    return []


def gate_holds() -> list[Judge]:
    """The capability-gate default: nothing compiled, nothing executed,
    no unknown refusals."""
    return [
        evaluator_is_installed,
        expect("executable_alloc_calls", "==", 0),
        expect("executable_alloc_bytes", "==", 0),
        expect("compiled_function_creations", "==", 0),
        expect("machine_code_entries", "==", 0),
        expect("machine_code_installed", "==", 0),
        expect("forced_deopt_hits", "==", 0),
        expect("organic_deopt_hits", "==", 0),
        expect("events_dropped", "==", 0),
        expect("supported_opcode_failures", "==", 0),
        expect("unknown_rejects", "==", 0),
        expect("live_compiled_functions_at_exit", "==", 0),
        expect("worker_crashes", "==", 0),
    ]


def shadow_holds(*, require_specialized: bool = False) -> list[Judge]:
    """A real shadow compile completed, but no executable state escaped."""
    judges = gate_holds() + [
        expect("compile_requests", ">", 0),
        expect("compile_success", ">", 0),
        expect("shadow_codegen_bytes", ">", 0),
        expect("peak_rss_bytes", ">", 0),
        requests_accounted(),
    ]
    if require_specialized:
        judges.append(expect("specialized_opcodes_consumed", ">", 0))
    return judges


# --------------------------------------------------------------------------
# Workload payloads

HOT_LOOP = """\
def hot(a, b):
    total = 0
    for i in range(a):
        total += i * b
    return total

for _ in range(ITERS):
    hot(50, 3)
"""

TARGET_EVENT_ASSERTION = """\
_target_events = [
    event for event in _cinderx._get_observe_stats()["events"]
    if event["qualname"] == TARGET_NAME
]
assert len(_target_events) == 1, (TARGET_NAME, _target_events)
assert _target_events[0]["count"] == TARGET_THRESHOLD, _target_events[0]
assert _target_events[0]["result"] == "compiled", _target_events[0]
"""


def target_event_assertion(mode: str = "shadow") -> str:
    """The scheduling event for the target function, per mode: shadow
    discards its compilation, execute (and its test spelling, canary)
    installs it."""
    if mode == "shadow":
        return TARGET_EVENT_ASSERTION
    return TARGET_EVENT_ASSERTION.replace(
        '"result"] == "compiled"', '"result"] == "installed"'
    )

# Execute-surface workload for the canary drivers: while-loop arithmetic
# with variable operands only.  x = x + CONST accumulator shapes stay
# behind the MR-03 policy valve.  CALL is on the MR-06 surface; this
# leaf stays CALL-free so the original MR-04 path remains attested.
CANARY_DEF = """\
def hot(a, b, one):
    total = a - a
    i = total
    while i < b:
        total = total + a
        if total > b * b:
            total = total - b
        i = i + one
    return total
"""

CANARY_ATTEST = """\
import cinderjit
assert cinderjit.is_attr_caches_enabled() is True, (
    'the 3.11 attribute-cache default is on since the MR-09 acceptance')
"""

# Loaded by every interpreter spawned by pyperformance. Only benchmark workers
# may initialize CinderX: venv-management processes also import sitecustomize,
# and running ensurepip/pip under the canary evaluator can crash before the
# benchmark starts. A temporary sitecustomize writes one frozen report per
# worker; the payload below rejects missing reports, supported-opcode failures,
# dropped events and every machine-code side effect.
_PYPERFORMANCE_WORKER_PROBE = """\
import atexit
import json
import os
import sys

# Nested pyperformance venvs use a different interpreter whose
# site-packages do not contain _cinderx.  The host-venv directory is
# passed in JIT311_CINDERX_SITE so worker sitecustomize can load the
# extension instead of printing ModuleNotFoundError onto pyperf stdout.
_cinderx_site = os.environ.get("JIT311_CINDERX_SITE")
if _cinderx_site:
    sys.path.insert(0, _cinderx_site)
sys.path.insert(0, os.environ["JIT311_REPO_ROOT"])
import _cinderx
import cinderx

cinderx.init()
if not _cinderx.is_frame_evaluator_installed():
    _cinderx.install_frame_evaluator()

def _jit311_nested_emit():
    installed = _cinderx.is_frame_evaluator_installed()
    # Same ordering contract as the primary emitter: the logical installed
    # count is only answerable while the evaluator is still in place.
    try:
        from cinderjit import get_compiled_functions
        _installed_at_exit = len(get_compiled_functions())
    except ImportError:
        _installed_at_exit = 0
    if installed:
        _cinderx.remove_frame_evaluator()
    from ci_pipeline.jit311 import report as _jit311_report
    snap = _jit311_report.snapshot()
    snap["machine_code_installed"] = _installed_at_exit
    snap["evaluator_installed"] = installed
    snap["pyperformance_worker"] = True
    # Attest the configuration this worker actually ran under.  Inheritance
    # through pyperformance's venv indirection is exactly the thing that
    # silently breaks, so the leg asserts these rather than assuming them.
    snap["jit_mode"] = os.environ.get("CINDERX_JIT_MODE")
    snap["pythonmalloc"] = os.environ.get("PYTHONMALLOC")
    _worker_ext = getattr(_cinderx, "__file__", None)
    snap["cinderx_file"] = os.path.realpath(_worker_ext) if _worker_ext else None
    if _worker_ext:
        import hashlib
        with open(_worker_ext, "rb") as _ext_fp:
            snap["cinderx_sha256"] = hashlib.sha256(_ext_fp.read()).hexdigest()
    else:
        snap["cinderx_sha256"] = None
    path = os.path.join(
        os.environ["JIT311_WORKER_REPORT_DIR"],
        "%d.json" % os.getpid(),
    )
    with open(path, "w", encoding="utf8") as fp:
        json.dump(snap, fp)

atexit.register(_jit311_nested_emit)
"""
PYPERFORMANCE_SITECUSTOMIZE = (
    "import sys\n"
    "if '--worker' in sys.argv:\n"
    + "\n".join(
        f"    {line}" for line in _PYPERFORMANCE_WORKER_PROBE.splitlines()
    )
    + "\n"
)

# RFC appendix B: immutable full-program-surface accounting list.  The
# stdlib runner imports these exact 72 Lib/test modules; a missing module is
# a worker failure, never an implicit coverage shrink.
STDLIB_SHADOW_MODULES = (
    "test_grammar", "test_types", "test_scope", "test_augassign",
    "test_unpack", "test_unpack_ex", "test_listcomps", "test_dictcomps",
    "test_fstring", "test_format", "test_with", "test_contextlib",
    "test_code", "test_dis", "test_int", "test_long", "test_float",
    "test_complex", "test_bool", "test_bytes", "test_dict", "test_set",
    "test_list", "test_tuple", "test_slice", "test_index", "test_binop",
    "test_richcmp", "test_range", "test_enumerate", "test_iter",
    "test_itertools", "test_sort", "test_call", "test_extcall",
    "test_builtin", "test_keywordonlyarg", "test_positional_only_arg",
    "test_functools", "test_descr", "test_property", "test_super",
    "test_class", "test_subclassinit", "test_metaclass", "test_abc",
    "test_isinstance", "test_enum", "test_dataclasses", "test_funcattrs",
    "test_exceptions", "test_raise", "test_except_star",
    "test_exception_group", "test_traceback", "test_frame", "test_inspect",
    "test_sys_settrace", "test_sys_setprofile", "test_cprofile",
    "test_generators", "test_genexps", "test_yield_from", "test_asyncgen",
    "test_coroutines", "test_contextlib_async", "test_gc", "test_weakref",
    "test_finalization", "test_copy", "test_pickle", "test_import",
)


def stdlib_shadow_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """Import the RFC's 72-module Lib/test canary under shadow.

    Import is the cheap MR-05 discovery canary. Completeness of the frozen
    440-module surface is the shadow-surface execution leg, which actually
    runs test functions and records per-module/case compile completeness.
    """
    payload = (
        "import importlib\n"
        f"_targets = {STDLIB_SHADOW_MODULES!r}\n"
        "assert len(_targets) == len(set(_targets)) == 72\n"
        "for _name in _targets:\n"
        "    _jit311_target_modules_attempted += 1\n"
        "    importlib.import_module('test.' + _name)\n"
    )
    default = shadow_holds() + [expect("target_modules_attempted", "==", 72)]
    return RunnerSpec(
        name="stdlib_shadow_72",
        payload=payload,
        env={"CINDERX_JIT_MODE": "shadow", "PYTHONJITAUTO": "1"},
        asserted_env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": "1",
        },
        judges=judges if judges is not None else default,
        target_modules_attempted=len(STDLIB_SHADOW_MODULES),
        timeout=1200,
    )


def stdlib_canary_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """The same 72-module import canary under canary EXECUTION: the
    aggressive threshold organically compiles and executes every eligible
    stdlib function met during import (MR-04 acceptance: no crashes, the
    ledger closed, machine code genuinely entered).  The debug allocator
    turns silent heap misuse into loud failures."""
    payload = (
        "import importlib\n"
        f"_targets = {STDLIB_SHADOW_MODULES!r}\n"
        "assert len(_targets) == len(set(_targets)) == 72\n"
        # A whole-process counter cannot say which module did anything.  Each
        # module is measured on its own: it must either have entered machine
        # code or have had every scheduling request answered by a named
        # refusal.  A module that produced neither is a module this leg did
        # not actually cover, and it is named rather than averaged away.
        "_per_module = {}\n"
        "_silent = []\n"
        "for _name in _targets:\n"
        "    _jit311_target_modules_attempted += 1\n"
        "    _before = _cinderx._get_trigger_stats()['machine_code_entries']\n"
        "    _events_before = len(_cinderx._get_observe_stats()['events'])\n"
        "    importlib.import_module('test.' + _name)\n"
        "    _entered = (_cinderx._get_trigger_stats()['machine_code_entries']\n"
        "                - _before)\n"
        "    _events = _cinderx._get_observe_stats()['events'][_events_before:]\n"
        "    _per_module[_name] = (_entered, len(_events))\n"
        "    if _entered == 0 and not _events:\n"
        "        _silent.append(_name)\n"
        "_covered = [n for n, (e, _) in _per_module.items() if e > 0]\n"
        "assert len(_covered) >= 8, (len(_covered), sorted(_per_module))\n"
        "print('jit311 canary stdlib: %d/%d modules entered machine code, '\n"
        "      '%d silent' % (len(_covered), len(_targets), len(_silent)))\n"
        "assert not _silent, _silent\n"
    )
    # This sweep measures import-time breadth on purpose: it imports 72
    # stdlib test modules and requires each to have reached the JIT.  That
    # is precisely what MR-11's import suppression prevents, so the sweep
    # runs with the providers off -- it is a coverage stress surface for
    # the compiler across 72 modules' worth of code shapes, not a model of
    # the product's startup, and the product's startup behaviour is what
    # the execute drivers and the 72-module differential measure.
    #
    # The organic count steps with each milestone: five in the MR-07 era,
    # one more when MR-08 opened the exception family, 333 once MR-09's
    # pull-validated attribute caches guard attribute sites across 72
    # importing modules (import-time class mutation retires
    # receiver-version guards by design), and 336 at the MR-11 base after
    # MR-10's generator round.  MR-11 itself leaves the count unchanged:
    # the base build and this branch measure alike in the gate's
    # invocation context.  The count is sensitive to sys.path (an extra
    # repository root on PYTHONPATH changes the compiled slice); the gate
    # runs with the venv only.  Verified deterministic across reruns; the
    # exact pin keeps the fail-closed drift guard.
    default = execute_holds(expected_organic_deopts=336) + [
        expect("compile_requests", ">", 0),
        expect("target_modules_attempted", "==", 72),
    ]
    return RunnerSpec(
        name="canary_stdlib_72",
        payload=payload,
        env={
            "CINDERX_JIT_MODE": "canary",
            "PYTHONJITAUTO": "1",
            "PYTHONMALLOC": "debug",
            # See above: this sweep is about import-time breadth.
            "CINDERX_AUTOJIT_IMPORT_PROVIDER": "off",
            "CINDERX_AUTOJIT_SETUP_PROVIDER": "off",
        },
        asserted_env={"CINDERX_JIT_MODE": "canary"},
        judges=judges if judges is not None else default,
        target_modules_attempted=len(STDLIB_SHADOW_MODULES),
        timeout=1800,
    )


def corpus_shadow_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """Execute every migrated RuntimeTests Python corpus case under shadow."""
    payload = (
        "from ci_pipeline.jit311 import corpus\n"
        "_ran = 0\n"
        "for _module, _case, _fn in corpus.iter_cases():\n"
        "    try:\n"
        "        _fn()\n"
        "    except (KeyboardInterrupt, SystemExit) as _exc:\n"
        "        raise AssertionError((_module, _case)) from _exc\n"
        "    except BaseException:\n"
        "        pass\n"
        "    _ran += 1\n"
        "assert _ran > 300, _ran\n"
    )
    return RunnerSpec(
        name="runtime_python_corpus",
        payload=payload,
        env={"CINDERX_JIT_MODE": "shadow", "PYTHONJITAUTO": "1"},
        asserted_env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": "1",
        },
        judges=judges if judges is not None else shadow_holds(),
        timeout=1200,
    )


def dynamic_shapes_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """Exercise closure, lambda, comprehension and dynamic-code frames."""
    payload = """\
def make_closure(bias):
    def closed(value):
        return value + bias
    return closed

closed = make_closure(3)
lam = lambda value: value * 2

def comprehensions(values):
    return (
        [value + 1 for value in values],
        {value: value * 2 for value in values},
        {value - 1 for value in values},
    )

namespace = {}
exec("def dynamic(value):\\n    return value ** 2", namespace)
dynamic = namespace["dynamic"]

assert closed(39) == 42
assert lam(21) == 42
assert comprehensions([1, 2]) == ([2, 3], {1: 2, 2: 4}, {0, 1})
assert dynamic(7) == 49

events = _cinderx._get_observe_stats()["events"]
compiled = {
    event["qualname"] for event in events if event["result"] == "compiled"
}
for expected in (
    "make_closure", "make_closure.<locals>.closed", "<lambda>",
    "comprehensions", "comprehensions.<locals>.<listcomp>",
    "comprehensions.<locals>.<dictcomp>",
    "comprehensions.<locals>.<setcomp>", "dynamic",
):
    assert expected in compiled, (expected, events)
"""
    return RunnerSpec(
        name="dynamic_code_shapes",
        payload=payload,
        env={"CINDERX_JIT_MODE": "shadow", "PYTHONJITAUTO": "1"},
        asserted_env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": "1",
        },
        judges=judges if judges is not None else shadow_holds(),
    )


# --------------------------------------------------------------------------
# Stage-appropriate drivers; later MRs extend the execution-specific judges.

def execute_holds(*, expected_organic_deopts: int = 0) -> list[Judge]:
    """The canary (MR-04) contract: machine code genuinely compiled,
    installed and entered, with the ledger closed -- and none of the
    shadow counters moving, because canary does not shadow-compile.
    Simplify can make organic deopt legitimate, but every deterministic
    runner pins its expected count so a deopt storm cannot wash green.
    Tests must not arm site-deopt on these runners."""
    return [
        expect("evaluator_installed", "==", True),
        expect("machine_code_entries", ">", 0),
        expect("executable_alloc_calls", ">", 0),
        expect("executable_alloc_bytes", ">", 0),
        expect("compiled_function_creations", ">", 0),
        expect("machine_code_installed", ">", 0),
        expect("live_compiled_functions_at_exit", ">", 0),
        expect("unknown_rejects", "==", 0),
        expect("events_dropped", "==", 0),
        expect("forced_deopt_hits", "==", 0),
        expect("organic_deopt_hits", "==", expected_organic_deopts),
        # In the schema the shadow-success counter surfaces as
        # compile_success; canary must not move it (no shadow compiles).
        expect("compile_success", "==", 0),
        expect("shadow_codegen_bytes", "==", 0),
        canary_requests_accounted(),
    ]


def canary_force_cold_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """force_compile before the first call, then execute machine code and
    hold the result equal to the interpreter's.

    Cold means cold: the target is compiled before it has ever run, so its
    bytecode carries no quickened form.  The interpreted oracle is a
    separate function with its own code object -- computing the expected
    values with the target itself would quicken it first and turn this into
    a second warm runner."""
    payload = CANARY_DEF + CANARY_ATTEST + (
        # An independent code object with the same body, used only as the
        # oracle.  Its own quickening is irrelevant to the target.
        "import dis\n"
        "oracle_src = ''.join(\n"
        "    line + chr(10) for line in "
        "%r.splitlines())\n"
        "oracle_ns = {}\n"
        "exec(oracle_src.replace('def hot(', 'def oracle('), oracle_ns)\n"
        "oracle = oracle_ns['oracle']\n"
        "expected = [oracle(i, 7, 1) for i in range(64)]\n"
        "assert all(i.opname == j.opname for i, j in zip(\n"
        "    dis.get_instructions(hot),\n"
        "    dis.get_instructions(hot, adaptive=True))), (\n"
        "    'target quickened before the cold compile')\n"
        "from cinderx import jit as _jit\n"
        "assert _jit.force_compile_cold(hot) is True, 'cold compile'\n"
        "assert cinderjit.is_jit_compiled(hot)\n"
        "for i in range(64):\n"
        "    assert hot(i, 7, 1) == expected[i], i\n"
    ) % CANARY_DEF
    return RunnerSpec(
        name="canary_force_cold",
        payload=payload,
        # The huge organic threshold keeps the interpreter-oracle loop
        # interpreted; only the explicit force_compile installs.
        env={
            "CINDERX_JIT_MODE": "canary",
            "PYTHONJITAUTO": "1000000",
            "PYTHONMALLOC": "debug",
        },
        asserted_env={"CINDERX_JIT_MODE": "canary"},
        judges=judges if judges is not None else execute_holds(),
    )


def canary_force_warm_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """Interpreter warm-up with verified quickening, then compile.

    The warm dimension this exercises is the warmed interpreter state:
    the child proves quickening actually happened before force_compile
    consumes the adaptive stream (specialized_opcodes is on since MR-07,
    so the compile may select guards from the specialized forms)."""
    payload = CANARY_DEF + CANARY_ATTEST + (
        "for _ in range(200):\n"
        "    hot(2, 9, 1)\n"
        "import dis\n"
        "plain = [i.opname for i in dis.get_instructions(hot)]\n"
        "adaptive = [i.opname for i in"
        " dis.get_instructions(hot, adaptive=True)]\n"
        "specialized = [b for a, b in zip(plain, adaptive) if a != b]\n"
        "assert 'BINARY_OP_ADD_INT' in specialized, specialized\n"
        "interp = hot(2, 9, 1)\n"
        "from cinderx import jit as _jit\n"
        "assert _jit.force_compile_warm(hot) is True, 'warm compile'\n"
        "assert hot(2, 9, 1) == interp\n"
    )
    return RunnerSpec(
        name="canary_force_warm",
        payload=payload,
        env={
            "CINDERX_JIT_MODE": "canary",
            "PYTHONJITAUTO": "1000000",
            "PYTHONMALLOC": "debug",
        },
        asserted_env={"CINDERX_JIT_MODE": "canary"},
        judges=judges if judges is not None else execute_holds(),
    )


def canary_execute_runner(
    *, threshold: int = 8, judges: list[Judge] | None = None
) -> RunnerSpec:
    """Organic canary dispatch: crossing the observe threshold compiles
    and installs without force_compile; the ledger records the request
    with the "installed" result."""
    payload = CANARY_DEF + CANARY_ATTEST + (
        "for i in range(40):\n"
        "    hot(i, 5, 1)\n"
        "assert cinderjit.is_jit_compiled(hot), 'threshold must install'\n"
        "assert hot(4, 5, 1) == 20\n"
        "assert hot(6, 5, 1) == 25\n"
    )
    # Zero organic deopts: import/setup suppression keeps the child
    # preamble's import machinery interpreted (see EXECUTE_AUTO_DEOPT_PIN).
    default = execute_holds(expected_organic_deopts=0) + [
        expect("compile_requests", ">", 0)
    ]
    return RunnerSpec(
        name="canary_execute",
        payload=payload,
        env={
            "CINDERX_JIT_MODE": "canary",
            "PYTHONJITAUTO": str(threshold),
            "PYTHONMALLOC": "debug",
        },
        asserted_env={"CINDERX_JIT_MODE": "canary"},
        judges=judges if judges is not None else default,
    )


# A nested function re-created per call: the shape 3.11 fresh attachment
# exists for.  Same execute-surface discipline as CANARY_DEF.
EXECUTE_FRESH_DEF = CANARY_DEF + """\
def factory(k):
    def adder(a, b, one):
        total = a - a
        i = total
        while i < b:
            total = total + a + k
            i = i + one
        return total
    return adder
"""


def execute_auto_runner(
    *, threshold: int = 8, judges: list[Judge] | None = None
) -> RunnerSpec:
    """The product mode (MR-11), spelled as the product spells it.

    An acceptance smoke: organic scheduling installs machine code under
    the product spelling, and a fresh instance attaches without a second
    compilation.  The fresh-attach CONTRACT (budget, flags, event ledger)
    is owned by test_execute_311.py; re-proving it here would track that
    suite, not the product."""
    payload = EXECUTE_FRESH_DEF + CANARY_ATTEST + (
        "_stats = _cinderx._get_observe_stats()\n"
        "assert _stats['mode'] == 'execute', _stats\n"
        "assert _stats['requested_mode'] == 'execute', _stats\n"
        "for i in range(40):\n"
        "    hot(i, 5, 1)\n"
        "assert cinderjit.is_jit_compiled(hot), 'threshold must install'\n"
        "assert hot(4, 5, 1) == 20\n"
        "_made = _cinderx._get_trigger_stats()['compiled_function_creations']\n"
        "_first = factory(1)\n"
        "for _ in range(12):\n"
        "    assert _first(2, 3, 1) == 3 * (2 + 1)\n"
        "assert cinderjit.is_jit_compiled(_first), 'threshold must install'\n"
        "_fresh = factory(2)\n"
        "assert _fresh(2, 3, 1) == 3 * (2 + 2)\n"
        "assert _fresh(2, 3, 1) == 3 * (2 + 2)\n"
        "assert cinderjit.is_jit_compiled(_fresh), 'fresh must attach'\n"
        "_after = _cinderx._get_trigger_stats()['compiled_function_creations']\n"
        "assert _after - _made == 1, (_made, _after)  # attach, not recompile\n"
    )
    default = execute_holds(expected_organic_deopts=EXECUTE_AUTO_DEOPT_PIN) + [
        expect("compile_requests", ">", 0)
    ]
    return RunnerSpec(
        name="execute_auto",
        payload=payload,
        env={
            "CINDERX_JIT_MODE": "execute",
            "PYTHONJITAUTO": str(threshold),
            "PYTHONMALLOC": "debug",
        },
        asserted_env={"CINDERX_JIT_MODE": "execute"},
        judges=judges if judges is not None else default,
    )


# Organic deopt pins for the execute-mode drivers.  All zero, and the
# attribution is import/setup suppression: every count these pins used to
# hold came from the child preamble's import machinery, which MR-11 no
# longer compiles.  Zero fails closed if import-time compilation returns.
EXECUTE_AUTO_DEOPT_PIN = 0
EXCEPTION_CORPUS = """\
class Erratic:
    def __init__(self, fail_at):
        self.fail_at = fail_at
        self.count = 0

    def tick(self):
        self.count = self.count + 1
        if self.count == self.fail_at:
            raise RuntimeError('inj-%d' % self.fail_at)
        return 1


class Guard:
    def __init__(self, log):
        self.log = log

    def __enter__(self):
        self.log.append('enter')
        return self

    def __exit__(self, exc_type, exc, tb):
        self.log.append('exit-%s' % (
            'none' if exc_type is None else exc_type.__name__))
        return False


def target(e, n, log):
    acc = n - n
    try:
        with Guard(log):
            i = acc
            while i < n:
                acc = acc + e.tick()
                i = i + 1
    except RuntimeError:
        log.append('caught')
        return -acc
    finally:
        log.append('fin')
    return acc


def run_target(fail_at, n):
    log = []
    result = target(Erratic(fail_at), n, log)
    return (result, log)
"""


def exception_semantics_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """MR-08: the exception surface executes and every raise deopts into
    the anchored evaluator's handler dispatch.

    An injection sweep moves the raising checkpoint across the whole body
    (each loop iteration, plus the never-raises arm), and every swept
    answer -- return value, handler choice, with/finally event order --
    must equal the interpreter's, recorded before any machine code
    existed.  Organic deopts are the mechanism, so the run must record
    some."""
    payload = CANARY_ATTEST + EXCEPTION_CORPUS + (
        "N = 6\n"
        "sweep = list(range(1, N + 2)) + [0]\n"
        "expected = {k: run_target(k, N) for k in sweep}\n"
        "assert cinderjit.force_compile(target) is True\n"
        "assert cinderjit.is_jit_compiled(target)\n"
        "for k in sweep:\n"
        "    got = run_target(k, N)\n"
        "    assert got == expected[k], (k, got, expected[k])\n"
        "    assert cinderjit.is_jit_compiled(target), (\n"
        "        'a handled exception must not uninstall the artifact')\n"
    )
    # Eight organic deopts: the corpus raises through compiled code by
    # design, and each raising form deopts exactly once (kUnhandledException
    # delegation).  The exact pin replaces the old ">0" judge so a deopt
    # storm cannot wash green.
    default = execute_holds(expected_organic_deopts=8)
    return RunnerSpec(
        name="exception_semantics",
        payload=payload,
        env={
            "CINDERX_JIT_MODE": "canary",
            "PYTHONJITAUTO": "1000000",
            "PYTHONMALLOC": "debug",
        },
        asserted_env={"CINDERX_JIT_MODE": "canary"},
        judges=judges if judges is not None else default,
    )


def cold_compile_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """Shadow compile the physical cold bytecode on the first entry."""
    payload = (
        "TARGET_NAME = 'jit311_cold_target'\n"
        "TARGET_THRESHOLD = 1\n"
        "def jit311_cold_target(a, b):\n"
        "    return a + b\n"
        "assert jit311_cold_target(20, 22) == 42\n"
        + TARGET_EVENT_ASSERTION
    )
    return RunnerSpec(
        name="cold_compile",
        payload=payload,
        env={"CINDERX_JIT_MODE": "shadow", "PYTHONJITAUTO": "1"},
        asserted_env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": "1",
        },
        judges=judges if judges is not None else shadow_holds(),
    )


def warm_compile_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """Quicken first, then shadow compile the physical specialized stream."""
    payload = (
        "import dis\n"
        "TARGET_NAME = 'jit311_warm_target'\n"
        "TARGET_THRESHOLD = 64\n"
        "WARMUP_CALLS = 32\n"
        "def jit311_warm_target(a, b):\n"
        "    return a + b\n"
        "for i in range(WARMUP_CALLS):\n"
        "    assert jit311_warm_target(i, 2) == i + 2\n"
        "_adaptive = dis.Bytecode(jit311_warm_target, adaptive=True).dis()\n"
        "assert 'BINARY_OP_ADD_INT' in _adaptive, _adaptive\n"
        "for i in range(TARGET_THRESHOLD - WARMUP_CALLS):\n"
        "    assert jit311_warm_target(i, 3) == i + 3\n"
        + TARGET_EVENT_ASSERTION
    )
    return RunnerSpec(
        name="warm_compile",
        payload=payload,
        env={"CINDERX_JIT_MODE": "shadow", "PYTHONJITAUTO": "64"},
        asserted_env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": "64",
        },
        judges=(
            judges
            if judges is not None
            else shadow_holds(require_specialized=True)
        ),
    )


def auto_like_runner(
    *,
    threshold: int = 30,
    iters: int | None = None,
    judges: list[Judge] | None = None,
) -> RunnerSpec:
    """Shadow requests raised organically by crossing the call threshold."""
    if iters is None:
        iters = threshold * 4
    payload = (
        f"ITERS = {iters}\n"
        f"TARGET_THRESHOLD = {threshold}\n"
        "TARGET_NAME = 'hot'\n"
        + HOT_LOOP
        + "assert hot(50, 3) == 3675\n"
        + TARGET_EVENT_ASSERTION
    )
    default = shadow_holds()
    return RunnerSpec(
        name="auto_like",
        payload=payload,
        env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": str(threshold),
        },
        asserted_env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": str(threshold),
        },
        judges=judges if judges is not None else default,
    )


def shadow_compile_runner(*, judges: list[Judge] | None = None) -> RunnerSpec:
    """Full compilation through codegen, followed by artifact discard."""
    payload = (
        "ITERS = 50\n"
        "TARGET_NAME = 'hot'\n"
        "TARGET_THRESHOLD = 20\n"
        + HOT_LOOP
        + "assert hot(50, 3) == 3675\n"
        + TARGET_EVENT_ASSERTION
    )
    return RunnerSpec(
        name="shadow_compile",
        payload=payload,
        env={"CINDERX_JIT_MODE": "shadow", "PYTHONJITAUTO": "20"},
        asserted_env={
            "CINDERX_JIT_MODE": "shadow",
            "PYTHONJITAUTO": "20",
        },
        judges=judges if judges is not None else shadow_holds(),
    )


def corpus_completeness_runner(
    *, expected_modules: int = 10, judges: list[Judge] | None = None
) -> RunnerSpec:
    """Completion contract over the migrated corpus: every corpus module
    must import and enumerate, and the module count is asserted inside the
    child against the manifest -- a silently missing module exits nonzero
    and turns red."""
    payload = f"""
from ci_pipeline.jit311 import corpus as _corpus
_modules = set()
_case_total = 0
for _module, _case_name, _fn in _corpus.iter_cases():
    _modules.add(_module)
    _case_total += 1
assert _case_total > 0
assert len(_modules) == {expected_modules}, (
    "corpus module surface shrank", sorted(_modules))
"""
    return RunnerSpec(
        name="corpus_completeness",
        payload=payload,
        judges=judges if judges is not None else gate_holds(),
    )

def load_libtest_target_manifest() -> list[str]:
    return [
        line.strip()
        for line in LIBTEST_TARGET_MANIFEST.read_text().splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


# The committed pyperformance tranche, pinned by size and identity so a
# silent shrink cannot pass the structural checks below.  The identity is
# the normalized manifest lines (task and result columns both), so renaming
# a result is as visible as dropping a task.
PYPERF_BENCHMARK_COUNT = 33
PYPERF_BENCHMARK_DIGEST = "314314a78a77f10a"


def load_pyperf_benchmarks() -> dict[str, tuple[str, ...]]:
    """The committed completion set, mapping each pyperformance TASK to the
    exact result names it must report (`task: result [result ...]` lines).

    The two columns live in different namespaces: --benchmarks selects
    tasks, but a task may emit several results and none under its own name
    (scimark reports scimark_sor, scimark_fft, ...).  Growing the set is a
    data edit, and the runner asserts the reported result-name set equals
    the manifest's expectation exactly."""
    mapping: dict[str, tuple[str, ...]] = {}
    seen_results: set[str] = set()
    identity_lines: list[str] = []
    for line in PYPERF_BENCHMARKS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        identity_lines.append(line)
        task, colon, results_field = line.partition(":")
        task = task.strip()
        results = tuple(results_field.split())
        if not colon or not task or not results:
            raise SystemExit(
                f"pyperf benchmark manifest line is not "
                f"'task: result [result ...]': {line!r} "
                f"({PYPERF_BENCHMARKS})"
            )
        if task in mapping:
            raise SystemExit(
                f"pyperf benchmark manifest duplicates task {task!r}: "
                f"{PYPERF_BENCHMARKS}"
            )
        for result in results:
            # A result name must sit under its task; anything else means
            # swapped columns or a foreign row, not a new benchmark.
            if result != task and not result.startswith(task + "_"):
                raise SystemExit(
                    f"pyperf manifest result {result!r} does not belong "
                    f"to task {task!r}: {PYPERF_BENCHMARKS}"
                )
            if result in seen_results:
                raise SystemExit(
                    f"pyperf benchmark manifest duplicates result "
                    f"{result!r}: {PYPERF_BENCHMARKS}"
                )
            seen_results.add(result)
        mapping[task] = results
    if not mapping:
        raise SystemExit(
            f"pyperf benchmark manifest is empty: {PYPERF_BENCHMARKS}"
        )
    # Structural checks alone would accept a manifest shrunk to one name.
    # The tranche's identity is part of what the completion legs claim, so
    # it is pinned here: shrinking or renaming it is a deliberate edit that
    # has to move this digest too.
    digest = hashlib.sha256(
        "\n".join(identity_lines).encode()).hexdigest()[:16]
    if len(mapping) != PYPERF_BENCHMARK_COUNT or (
        digest != PYPERF_BENCHMARK_DIGEST
    ):
        raise SystemExit(
            f"pyperf benchmark tranche drifted: {len(mapping)} task(s), "
            f"digest {digest}; the pinned tranche is "
            f"{PYPERF_BENCHMARK_COUNT} task(s), digest "
            f"{PYPERF_BENCHMARK_DIGEST}.  Edit the pin in the same change "
            f"that edits {PYPERF_BENCHMARKS.name}."
        )
    return mapping


def pyperf_completion_errors(
    expected: set[str], reported: set[str]
) -> list[str]:
    """Judge a pyperformance run's reported result names against the
    manifest expectation.  Exact equality in both directions: a missing
    name is an incomplete task, and an unexpected name is tool or manifest
    drift that must be an explicit same-change edit of the pin and the
    manifest."""
    errors = []
    missing = expected - reported
    if missing:
        errors.append(
            "expected results not reported (task did not complete): "
            f"{sorted(missing)!r}"
        )
    unexpected = reported - expected
    if unexpected:
        errors.append(
            "results outside the manifest (tool/manifest drift; update "
            f"the pin and the manifest together): {sorted(unexpected)!r}"
        )
    return errors


def discover_all_pyperf_benchmarks() -> list[str]:
    """The provisioned pyperformance's own applicable set, one name per
    entry.  `-b all` hides which benchmark died; iterating names keeps
    that identity in the assertion."""
    proc = subprocess.run(
        [sys.executable, "-m", "pyperformance", "list"],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(
            f"pyperformance list failed: {proc.stderr[-400:]}"
        )
    names = [
        line.strip()[2:].strip()
        for line in proc.stdout.splitlines()
        if line.strip().startswith("- ")
    ]
    if not names or len(names) != len(set(names)):
        raise SystemExit(
            f"pyperformance list produced no unique benchmarks: {names!r}"
        )
    return names


def pyperformance_completeness_runner(
    *, mode: str = "shadow", benchmarks: list[str] | None = None
) -> RunnerSpec | None:
    """Completion-oriented pyperformance leg: benchmarks must finish with
    zero worker crashes.  Returns None when pyperformance is unavailable;
    the caller decides whether that is acceptable for its stage (the gate
    treats unavailability as a skip only in developer runs, never in the
    stage-exit matrix)."""
    try:
        import pyperformance  # noqa: F401
    except ImportError:
        return None
    names = benchmarks or ["nbody"]
    payload = (
        "import json, os, pathlib, subprocess, sys, tempfile\n"
        "ITERS = 120\n"
        "TARGET_NAME = 'hot'\n"
        "TARGET_THRESHOLD = 30\n"
        + (
            HOT_LOOP + "assert hot(50, 3) == 3675\n"
            if mode == "shadow"
            # HOT_LOOP reaches a global and calls it, both outside the
            # execute surface, so the canary arm drives the surface-clean
            # workload instead and expects an install rather than a
            # discarded compilation.
            else CANARY_DEF
            + "for _ in range(ITERS):\n"
            + "    hot(4, 5, 1)\n"
            + "assert hot(4, 5, 1) == 20\n"
        )
        + target_event_assertion(mode)
        + f"_sitecustomize_source = {PYPERFORMANCE_SITECUSTOMIZE!r}\n"
        f"_benchmarks = {names!r}\n"
        "import hashlib\n"
        "_host_cinderx = os.path.realpath(_cinderx.__file__)\n"
        "_host_sha = hashlib.sha256(\n"
        "    open(_host_cinderx, 'rb').read()).hexdigest()\n"
        "_pip_keys = tuple(k for k in os.environ if k.startswith('PIP_'))\n"
        "_inherit = ','.join((\n"
        "    'CINDERX_PLUGIN_ENABLE', 'CINDERX_EVAL_MODE',\n"
        "    'CINDERX_JIT_MODE', 'PYTHONJITAUTO', 'PYTHONMALLOC',\n"
        "    'JIT311_REPO_ROOT', 'JIT311_WORKER_REPORT_DIR',\n"
        "    'JIT311_CINDERX_SITE',\n"
        "    'PYTHONPATH', 'LD_LIBRARY_PATH',\n"
        ") + _pip_keys)\n"
        "with tempfile.TemporaryDirectory(prefix='jit311-pyperf-') as _tmp:\n"
        "    _root = pathlib.Path(_tmp)\n"
        "    _reports = _root / 'reports'\n"
        "    _reports.mkdir()\n"
        "    (_root / 'sitecustomize.py').write_text(\n"
        "        _sitecustomize_source, encoding='utf8')\n"
        "    _nested_env = dict(os.environ)\n"
        "    _nested_env['JIT311_WORKER_REPORT_DIR'] = str(_reports)\n"
        "    _nested_env['JIT311_CINDERX_SITE'] = os.path.dirname(\n"
        "        _cinderx.__file__)\n"
        "    _nested_env['PYTHONPATH'] = os.pathsep.join(\n"
        "        (str(_root), _nested_env.get('PYTHONPATH', '')))\n"
        "    _seen = set()\n"
        "    _worker_entries = 0\n"
        "    _worker_organic_deopts = 0\n"
        "    _worker_requests = 0\n"
        "    for name in _benchmarks:\n"
        "        proc = subprocess.run(\n"
        "        [sys.executable, '-m', 'pyperformance', 'run',\n"
        "         '--debug-single-value', '-b', name,\n"
        "         '--inherit-environ', _inherit],\n"
        "        env=_nested_env, capture_output=True, timeout=1200)\n"
        "        assert proc.returncode == 0, (\n"
        "            name, proc.returncode, proc.stderr[-4000:])\n"
        "        _current = set(_reports.glob('*.json'))\n"
        "        _new = _current - _seen\n"
        "        assert _new, ('no pyperformance worker reports', name)\n"
        "        _raw_snaps = [json.loads(p.read_text(encoding='utf8'))\n"
        "                      for p in _new]\n"
        "        _workers = [s for s in _raw_snaps\n"
        "                    if s.get('pyperformance_worker') is True]\n"
        "        assert _workers, ('no real pyperformance worker reports', name)\n"
        + (
            "        assert any(s['compile_success'] > 0 for s in _workers), (\n"
            "            'benchmark workers never shadow-compiled', name)\n"
            if mode == "shadow"
            else
            # Whether a given benchmark contains a function inside the
            # execute surface is workload-dependent, so machine-code entry
            # cannot be required of every worker.  What can be required is
            # that the workers are not silently idle: either some worker
            # entered machine code, or every scheduling request they made
            # was answered by a named refusal.  Zero requests and zero
            # entries together is the fail-open case this rejects.
            "        _entered = sum(s['machine_code_entries']\n"
            "                       for s in _workers)\n"
            "        _requested = sum(s['compile_requests'] for s in _workers)\n"
            "        _refused = sum(s['compile_rejected'] for s in _workers)\n"
            "        _organic = sum(s['organic_deopt_hits']\n"
            "                       for s in _workers)\n"
            "        _worker_entries += _entered\n"
            "        _worker_organic_deopts += _organic\n"
            "        _worker_requests += _requested\n"
            "        assert _organic <= _entered, (\n"
            "            'worker deopts exceed machine-code entries',\n"
            "            name, _organic, _entered)\n"
            "        assert _entered > 0 or (_requested > 0\n"
            "                                and _requested == _refused), (\n"
            "            'workers neither executed machine code nor refused',\n"
            "            name, _entered, _requested, _refused)\n"
        )
        + "        for snap in _raw_snaps:\n"
        "            assert isinstance(snap.pop('pyperformance_worker'), bool)\n"
        "            assert snap['evaluator_installed'] is True, snap\n"
        f"            assert snap['jit_mode'] == {mode!r}, snap\n"
        "            assert snap['pythonmalloc'] == 'debug', snap\n"
        "            assert snap['cinderx_file'] == _host_cinderx, (\n"
        "                'worker loaded a different cinderx extension',\n"
        "                snap['cinderx_file'], _host_cinderx)\n"
        "            assert snap['cinderx_sha256'] == _host_sha, (\n"
        "                'worker extension content differs from the host',\n"
        "                snap['cinderx_sha256'], _host_sha)\n"
        "            assert snap['events_dropped'] == 0, snap\n"
        "            assert snap['supported_opcode_failures'] == 0, snap\n"
        "            assert snap['unknown_rejects'] == 0, snap\n"
        + (
            "            assert snap['compile_requests'] == (\n"
            "                snap['compile_success'] + snap['compile_rejected']\n"
            "            ), snap\n"
            if mode == "shadow"
            else
            # Canary answers a scheduling request by installing machine
            # code, so the closure runs through compile_installed; the
            # shadow-compile counter must stay still.
            "            assert snap['compile_requests'] == (\n"
            "                snap['compile_installed'] + snap['compile_rejected']\n"
            "            ), snap\n"
            "            assert snap['compile_success'] == 0, snap\n"
        )
        + (
            "            for field in (\n"
            "                'executable_alloc_calls', 'executable_alloc_bytes',\n"
            "                'compiled_function_creations',\n"
            "                'machine_code_installed', 'machine_code_entries'):\n"
            "                assert snap[field] == 0, (field, snap)\n"
            if mode == "shadow"
            else
            # canary: machine code may genuinely move in the driver
            # process; the ledger closure above is the contract.
            "            pass\n"
        )
        + "        _seen = _current\n"
        + (
            ""
            if mode == "shadow"
            else
            # Per benchmark, a refusal-only outcome is legitimate: whether a
            # workload contains a function inside the execute surface is a
            # property of the workload.  Across the whole tranche it is not
            # -- that would mean the leg ran pyperformance without ever
            # executing MR-04 machine code in a benchmark process, and said
            # nothing about it.
            "    assert _worker_entries > 0, (\n"
            "        'no benchmark worker entered machine code across the "
            "whole tranche', _worker_requests)\n"
            "    assert _worker_organic_deopts < _worker_entries, (\n"
            "        'every benchmark machine-code entry deoptimized',\n"
            "        _worker_organic_deopts, _worker_entries)\n"
            "    print('jit311 canary workers: entries=%d organic=%d "
            "requests=%d'\n"
            "          % (_worker_entries, _worker_organic_deopts,\n"
            "             _worker_requests))\n"
        )
    )
    if mode == "shadow":
        mode_judges = shadow_holds()
    else:
        # execute/canary driver-process contract: the driver's own target
        # is surface-clean and crosses the threshold, so machine code must
        # genuinely be entered here; the ledger closes and no shadow
        # counter moves.  The driver's organic deopts are bounded, not
        # pinned: the driver compiles whatever standard-library machinery
        # its benchmark list makes hot (subprocess, json, pathlib), and the
        # exception and attribute-cache surfaces deopt organically there.
        mode_judges = [
            expect("evaluator_installed", "==", True),
            expect("machine_code_entries", ">", 0),
            expect("machine_code_installed", ">", 0),
            canary_requests_accounted(),
            expect("unknown_rejects", "==", 0),
            expect("events_dropped", "==", 0),
            expect("forced_deopt_hits", "==", 0),
            organic_deopts_bounded_by_entries(),
            expect("compile_success", "==", 0),
            expect("shadow_codegen_bytes", "==", 0),
        ]
    return RunnerSpec(
        name=f"pyperformance_completeness_{mode}",
        payload=payload,
        env={
            "CINDERX_PLUGIN_ENABLE": "1",
            "CINDERX_EVAL_MODE": "cinder",
            "CINDERX_JIT_MODE": mode,
            "PYTHONJITAUTO": "30",
            "PYTHONMALLOC": "debug",
        },
        asserted_env={
            "CINDERX_PLUGIN_ENABLE": "1",
            "CINDERX_EVAL_MODE": "cinder",
            "CINDERX_JIT_MODE": mode,
            "PYTHONJITAUTO": "30",
        },
        judges=mode_judges,
        timeout=14400,
    )


def unify(fields_path: str, out_path: str) -> int:
    """Assemble the unified run report as a real artifact: a fresh gate
    child supplies the runtime snapshot, the libtest leg's emission
    supplies the module surface, and strict validation refuses any field
    that is missing or null."""
    spec = cold_compile_runner()
    result = run(spec)
    if not result.ok or result.report is None:
        for err in result.errors:
            print(f"unified-report: gate child failed: {err}")
        return 1
    unified = dict(result.report)
    unified["target_modules_attempted"] = None
    unified["worker_crashes"] = None
    try:
        fields = json.loads(Path(fields_path).read_text())
    except OSError as exc:
        print(f"unified-report: cannot read leg emission: {exc}")
        return 1
    foreign = set(fields) - {"target_modules_attempted", "worker_crashes"}
    if foreign:
        print(f"unified-report: leg emitted non-leg fields: {foreign}")
        return 1
    unified.update(fields)
    errors = _report.validate_schema(unified, strict=True)
    frozen = len(load_libtest_target_manifest())
    if not errors:
        if unified["target_modules_attempted"] != frozen:
            errors.append(
                f"target_modules_attempted must equal the frozen manifest "
                f"({frozen}), got {unified['target_modules_attempted']}"
            )
        if unified["worker_crashes"] != 0:
            errors.append(
                f"worker_crashes must be zero, got "
                f"{unified['worker_crashes']}"
            )
    if errors:
        for err in errors:
            print(f"unified-report: {err}")
        return 1
    Path(out_path).write_text(
        json.dumps(unified, indent=1, sort_keys=True) + "\n"
    )
    print(
        f"unified-report: all fields strictly typed, "
        f"target_modules_attempted="
        f"{unified['target_modules_attempted']}"
    )
    return 0


def run_all(python: str | None = None) -> list[RunResult]:
    """Run the battery: the shadow expectations and the canary/execute
    trigger-proof drivers.  Lifecycle, generator, shutdown and threshold
    scenarios live with their canonical owners (RuntimeTests, the corpus
    under the refcount matrix, the lifecycle census and the acceptance
    profile), not here."""
    specs: list[RunnerSpec] = [
        cold_compile_runner(),
        warm_compile_runner(),
        auto_like_runner(),
        shadow_compile_runner(),
        stdlib_shadow_runner(),
        corpus_shadow_runner(),
        dynamic_shapes_runner(),
    ]
    specs += [
        canary_force_cold_runner(),
        canary_force_warm_runner(),
        canary_execute_runner(),
        execute_auto_runner(),
        exception_semantics_runner(),
        stdlib_canary_runner(),
    ]
    results = [run(spec, python=python) for spec in specs]
    return results


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if "--unify" in argv:
        try:
            fields_path = argv[argv.index("--unify") + 1]
            out_path = argv[argv.index("-o") + 1]
        except (ValueError, IndexError):
            print("usage: runners --unify <fields.json> -o <out.json>")
            return 2
        return unify(fields_path, out_path)
    # `--pyperf` is a prefix of `--pyperformance-all`; dispatch on exact
    # tokens, and handle the full applicable set first so the daily job
    # cannot silently shrink to the 33-name tranche.
    if "--pyperformance-all" in argv:
        spec = pyperformance_completeness_runner(
            benchmarks=discover_all_pyperf_benchmarks()
        )
        if spec is None:
            print(
                "jit311-runners: pyperformance is required for the daily "
                "shadow gate",
                file=sys.stderr,
            )
            return 2
        result = run(spec)
        print(result.summary())
        return 0 if result.ok else 1
    if "--pyperf-execute-all" in argv:
        # MR-11: the execute leg covers the full applicable set, in the
        # product spelling, for several consecutive rounds -- the
        # acceptance is zero worker crashes in every round, not in one.
        rounds = 3
        if "--rounds" in argv:
            try:
                rounds = int(argv[argv.index("--rounds") + 1])
            except (ValueError, IndexError):
                print("usage: runners --pyperf-execute-all [--rounds N]")
                return 2
        if rounds < 1:
            print("jit311-runners: --rounds must be a positive integer")
            return 2
        names = discover_all_pyperf_benchmarks()
        spec = pyperformance_completeness_runner(mode="execute", benchmarks=names)
        if spec is None:
            print(
                "jit311-runners: pyperformance is required for the execute "
                "completion leg",
                file=sys.stderr,
            )
            return 2
        print(
            f"jit311-runners: execute completion leg covers all "
            f"{len(names)} applicable benchmark(s), {rounds} round(s)"
        )
        failed = 0
        for round_index in range(1, rounds + 1):
            round_spec = RunnerSpec(
                name=f"{spec.name}_round_{round_index}_of_{rounds}",
                payload=spec.payload,
                env=dict(spec.env),
                judges=list(spec.judges),
                expect_report=spec.expect_report,
                asserted_env=dict(spec.asserted_env),
                expect_returncode=spec.expect_returncode,
                expect_stderr_contains=spec.expect_stderr_contains,
                timeout=spec.timeout,
                target_modules_attempted=spec.target_modules_attempted,
            )
            result = run(round_spec)
            print(result.summary())
            if not result.ok:
                failed += 1
        print(
            f"jit311-runners: execute completion rounds "
            f"{rounds - failed}/{rounds} passed"
        )
        return 1 if failed else 0
    if "--stdlib-canary" in argv:
        result = run(stdlib_canary_runner())
        print(result.summary())
        if result.report is not None:
            keys = (
                "compile_requests",
                "compile_installed",
                "compile_rejected",
                "machine_code_entries",
                "machine_code_installed",
                "compiled_function_creations",
                "unknown_rejects",
                "organic_deopt_hits",
                "forced_deopt_hits",
                "target_modules_attempted",
                "live_compiled_functions_at_exit",
            )
            for key in keys:
                print("%s=%r" % (key, result.report.get(key)))
        return 0 if result.ok else 1
    if "--pyperf-canary" in argv:
        # The canary leg runs the committed tranche, not the full applicable
        # set the shadow daily covers: every benchmark here compiles and
        # executes machine code, which the nightly budget cannot absorb for
        # the whole set.  Say so out loud -- a bounded run that reads as
        # full coverage is how a gate starts lying.
        canary_names = load_pyperf_benchmarks()
        # The cap is deliberate, so it is stated as a fact the leg checks
        # rather than a line it prints.  Swallowing a discovery failure
        # would delete the "of N applicable" half and let a bounded run
        # read as full coverage.
        discoverable = len(discover_all_pyperf_benchmarks())
        if not discoverable:
            print(
                "jit311-runners: pyperformance reported no applicable "
                "benchmarks; the canary coverage claim cannot be checked",
                file=sys.stderr,
            )
            return 1
        if len(canary_names) > discoverable:
            print(
                f"jit311-runners: the canary tranche ({len(canary_names)}) "
                f"exceeds the applicable set ({discoverable})",
                file=sys.stderr,
            )
            return 1
        print(
            f"jit311-runners: canary completion leg covers "
            f"{len(canary_names)} of {discoverable} applicable benchmark(s); "
            f"the remainder is covered by the shadow completeness leg"
        )
        spec = pyperformance_completeness_runner(
            mode="canary", benchmarks=list(canary_names)
        )
        if spec is None:
            print(
                "jit311-runners: pyperformance is not provisioned in this "
                "environment; the canary completion leg cannot run",
                file=sys.stderr,
            )
            return 1
        result = run(spec)
        print(result.summary())
        return 0 if result.ok else 1
    if "--pyperf" in argv:
        spec = pyperformance_completeness_runner(
            benchmarks=list(load_pyperf_benchmarks())
        )
        if spec is None:
            print(
                "jit311-runners: pyperformance is not provisioned in this "
                "environment; the completeness leg cannot run (provision "
                "the runner venv with the pinned pyperformance package)",
                file=sys.stderr,
            )
            return 1
        result = run(spec)
        print(result.summary())
        return 0 if result.ok else 1
    if "--shadow-surface" in argv:
        from ci_pipeline.jit311.shadow_surface import main as surface_main

        rest = [arg for arg in argv if arg != "--shadow-surface"]
        return surface_main(rest)

    results = run_all()
    failed = [r for r in results if not r.ok]
    for result in results:
        print(result.summary())
    print(
        f"jit311-runners: {len(results) - len(failed)}/{len(results)} passed"
    )
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
