// Copyright (c) Meta Platforms, Inc. and affiliates.

#pragma once

#include "cinderx/python.h"

// Define all bytecodes that appeared or were removed from <lowest version of
// Python we support> and <highest version of Python we support>. Bytecodes that
// don't match the Python version being used for the current build will be
// intentionally defined to out-of-range values (i.e. >255) so as to not be
// reachable by the interpreter, or any utilities that read or write to code
// objects.
//
// Having them defined across all builds means there can be less Python version
// checks in the compiler.

#if PY_VERSION_HEX < 0x030C0000

#define STUB_OPCODE_DEFS(X)                    \
  X(BINARY_ADD)                                \
  X(BINARY_AND)                                \
  X(BINARY_FLOOR_DIVIDE)                       \
  X(BINARY_LSHIFT)                             \
  X(BINARY_MATRIX_MULTIPLY)                    \
  X(BINARY_MODULO)                             \
  X(BINARY_MULTIPLY)                           \
  X(BINARY_OP_SUBSCR_DICT)                     \
  X(BINARY_OP_SUBSCR_LIST_INT)                 \
  X(BINARY_OP_SUBSCR_TUPLE_INT)                \
  X(BINARY_OR)                                 \
  X(BINARY_POWER)                              \
  X(BINARY_RSHIFT)                             \
  X(BINARY_SLICE)                              \
  X(BINARY_SUBSCR_DICT_STR)                    \
  X(BINARY_SUBSCR_LIST)                        \
  X(BINARY_SUBSCR_TUPLE)                       \
  X(BINARY_SUBSCR_TUPLE_CONST_INT)             \
  X(BINARY_SUBTRACT)                           \
  X(BINARY_TRUE_DIVIDE)                        \
  X(BINARY_XOR)                                \
  X(BUILD_INTERPOLATION)                       \
  X(BUILD_TEMPLATE)                            \
  X(CALL_FUNCTION)                             \
  X(CALL_FUNCTION_KW)                          \
  X(CALL_INTRINSIC_1)                          \
  X(CALL_INTRINSIC_2)                          \
  X(CALL_KW)                                   \
  X(CALL_METHOD)                               \
  X(CLEANUP_THROW)                             \
  X(COMPARE_OP_FLOAT)                          \
  X(COMPARE_OP_INT)                            \
  X(COMPARE_OP_STR)                            \
  X(CONVERT_VALUE)                             \
  X(COPY_DICT_WITHOUT_KEYS)                    \
  X(DUP_TOP)                                   \
  X(DUP_TOP_TWO)                               \
  X(EAGER_IMPORT_NAME)                         \
  X(END_SEND)                                  \
  X(FORMAT_WITH_SPEC)                          \
  X(FORMAT_SIMPLE)                             \
  X(EXTENDED_OPCODE)                           \
  X(GEN_START)                                 \
  X(INPLACE_ADD)                               \
  X(INPLACE_AND)                               \
  X(INPLACE_FLOOR_DIVIDE)                      \
  X(INPLACE_LSHIFT)                            \
  X(INPLACE_MATRIX_MULTIPLY)                   \
  X(INPLACE_MODULO)                            \
  X(INPLACE_MULTIPLY)                          \
  X(INPLACE_OR)                                \
  X(INPLACE_POWER)                             \
  X(INPLACE_RSHIFT)                            \
  X(INPLACE_SUBTRACT)                          \
  X(INPLACE_TRUE_DIVIDE)                       \
  X(INPLACE_XOR)                               \
  X(JUMP_ABSOLUTE)                             \
  X(JUMP_IF_NOT_EXC_MATCH)                     \
  X(LOAD_ATTR_DICT_DESCR)                      \
  X(LOAD_ATTR_DICT_NO_DESCR)                   \
  X(LOAD_ATTR_NO_DICT_DESCR)                   \
  X(LOAD_ATTR_POLYMORPHIC)                     \
  X(LOAD_ATTR_SPLIT_DICT)                      \
  X(LOAD_ATTR_SPLIT_DICT_DESCR)                \
  X(LOAD_ATTR_SUPER)                           \
  X(LOAD_ATTR_S_MODULE)                        \
  X(LOAD_ATTR_TYPE)                            \
  X(LOAD_ATTR_UNCACHABLE)                      \
  X(LOAD_COMMON_CONSTANT)                      \
  X(LOAD_FAST_BORROW)                          \
  X(LOAD_FAST_BORROW_LOAD_FAST_BORROW)         \
  X(LOAD_FAST_LOAD_FAST)                       \
  X(LOAD_FAST_AND_CLEAR)                       \
  X(LOAD_FAST_CHECK)                           \
  X(LOAD_METHOD_DICT_DESCR)                    \
  X(LOAD_METHOD_DICT_METHOD)                   \
  X(LOAD_METHOD_NO_DICT_DESCR)                 \
  X(LOAD_METHOD_NO_DICT_METHOD)                \
  X(LOAD_METHOD_SPLIT_DICT_DESCR)              \
  X(LOAD_METHOD_SPLIT_DICT_METHOD)             \
  X(LOAD_METHOD_SUPER)                         \
  X(LOAD_METHOD_S_MODULE)                      \
  X(LOAD_METHOD_TYPE)                          \
  X(LOAD_METHOD_TYPE_METHODLIKE)               \
  X(LOAD_METHOD_UNCACHABLE)                    \
  X(LOAD_METHOD_UNSHADOWED_METHOD)             \
  X(LOAD_SMALL_INT)                            \
  X(LOAD_SPECIAL)                              \
  X(LOAD_SUPER_ATTR)                           \
  X(MAKE_OPNAME)                               \
  X(NOT_TAKEN)                                 \
  X(POP_ITER)                                  \
  X(POP_JUMP_IF_FALSE)                         \
  X(POP_JUMP_IF_NONE)                          \
  X(POP_JUMP_IF_NOT_NONE)                      \
  X(POP_JUMP_IF_TRUE)                          \
  X(POP_BLOCK)                                 \
  X(ROT_FOUR)                                  \
  X(ROT_N)                                     \
  X(ROT_THREE)                                 \
  X(ROT_TWO)                                   \
  X(SETUP_ASYNC_WITH)                          \
  X(SETUP_WITH)                                \
  X(END_FOR)                                   \
  X(RETURN_CONST)                              \
  X(SETUP_FINALLY)                             \
  X(STORE_ATTR_DESCR)                          \
  X(STORE_ATTR_DICT)                           \
  X(STORE_ATTR_SPLIT_DICT)                     \
  X(SET_FUNCTION_ATTRIBUTE)                    \
  X(STORE_ATTR_UNCACHABLE)                     \
  X(STORE_SLICE)                               \
  X(STORE_FAST_STORE_FAST)                     \
  X(STORE_FAST_LOAD_FAST)                      \
  X(TO_BOOL)                                   \
  X(YIELD_FROM)                                \
  X(JUMP_IF_ZERO_OR_POP)                       \
  X(JUMP_IF_NONZERO_OR_POP)                    \
  X(ANNOTATIONS_PLACEHOLDER)                   \
  X(BINARY_OP_EXTEND)                          \
  X(BINARY_OP_SUBSCR_GETITEM)                  \
  X(BINARY_OP_SUBSCR_LIST_SLICE)               \
  X(BINARY_OP_SUBSCR_STR_INT)                  \
  X(BUILD_CHECKED_LIST)                        \
  X(BUILD_CHECKED_LIST_CACHED)                 \
  X(BUILD_CHECKED_MAP)                         \
  X(BUILD_CHECKED_MAP_CACHED)                  \
  X(CALL_ALLOC_AND_ENTER_INIT)                 \
  X(CALL_BOUND_METHOD_EXACT_ARGS)              \
  X(CALL_BOUND_METHOD_GENERAL)                 \
  X(CALL_BUILTIN_CLASS)                        \
  X(CALL_BUILTIN_FAST)                         \
  X(CALL_BUILTIN_FAST_WITH_KEYWORDS)           \
  X(CALL_BUILTIN_O)                            \
  X(CALL_ISINSTANCE)                           \
  X(CALL_KW_BOUND_METHOD)                      \
  X(CALL_KW_NON_PY)                            \
  X(CALL_KW_PY)                                \
  X(CALL_LEN)                                  \
  X(CALL_LIST_APPEND)                          \
  X(CALL_METHOD_DESCRIPTOR_FAST)               \
  X(CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS) \
  X(CALL_METHOD_DESCRIPTOR_NOARGS)             \
  X(CALL_METHOD_DESCRIPTOR_O)                  \
  X(CALL_NON_PY_GENERAL)                       \
  X(CALL_PY_GENERAL)                           \
  X(CALL_STR_1)                                \
  X(CALL_TUPLE_1)                              \
  X(CALL_TYPE_1)                               \
  X(CAST)                                      \
  X(CAST_CACHED)                               \
  X(CONTAINS_OP_DICT)                          \
  X(CONTAINS_OP_SET)                           \
  X(CONVERT_PRIMITIVE)                         \
  X(ENTER_EXECUTOR)                            \
  X(EXIT_INIT_CHECK)                           \
  X(FAST_LEN)                                  \
  X(FOR_ITER_GEN)                              \
  X(FOR_ITER_LIST)                             \
  X(FOR_ITER_RANGE)                            \
  X(FOR_ITER_TUPLE)                            \
  X(INSTRUMENTED_CALL)                         \
  X(INSTRUMENTED_CALL_FUNCTION_EX)             \
  X(INSTRUMENTED_CALL_KW)                      \
  X(INSTRUMENTED_END_ASYNC_FOR)                \
  X(INSTRUMENTED_END_FOR)                      \
  X(INSTRUMENTED_END_SEND)                     \
  X(INSTRUMENTED_FOR_ITER)                     \
  X(INSTRUMENTED_INSTRUCTION)                  \
  X(INSTRUMENTED_JUMP_BACKWARD)                \
  X(INSTRUMENTED_JUMP_FORWARD)                 \
  X(INSTRUMENTED_LINE)                         \
  X(INSTRUMENTED_LOAD_SUPER_ATTR)              \
  X(INSTRUMENTED_NOT_TAKEN)                    \
  X(INSTRUMENTED_POP_ITER)                     \
  X(INSTRUMENTED_POP_JUMP_IF_FALSE)            \
  X(INSTRUMENTED_POP_JUMP_IF_NONE)             \
  X(INSTRUMENTED_POP_JUMP_IF_NOT_NONE)         \
  X(INSTRUMENTED_POP_JUMP_IF_TRUE)             \
  X(INSTRUMENTED_RESUME)                       \
  X(INSTRUMENTED_RETURN_VALUE)                 \
  X(INSTRUMENTED_YIELD_VALUE)                  \
  X(INTERPRETER_EXIT)                          \
  X(INVOKE_FUNCTION)                           \
  X(INVOKE_FUNCTION_CACHED)                    \
  X(INVOKE_INDIRECT_CACHED)                    \
  X(INVOKE_METHOD)                             \
  X(INVOKE_NATIVE)                             \
  X(JUMP)                                      \
  X(JUMP_BACKWARD_JIT)                         \
  X(JUMP_BACKWARD_NO_JIT)                      \
  X(JUMP_IF_FALSE)                             \
  X(JUMP_IF_TRUE)                              \
  X(JUMP_NO_INTERRUPT)                         \
  X(LIST_DEL)                                  \
  X(LOAD_ATTR_CLASS)                           \
  X(LOAD_ATTR_CLASS_WITH_METACLASS_CHECK)      \
  X(LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN)         \
  X(LOAD_ATTR_METHOD_LAZY_DICT)                \
  X(LOAD_ATTR_METHOD_NO_DICT)                  \
  X(LOAD_ATTR_METHOD_WITH_VALUES)              \
  X(LOAD_ATTR_NONDESCRIPTOR_NO_DICT)           \
  X(LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES)       \
  X(LOAD_ATTR_PROPERTY)                        \
  X(LOAD_CLASS)                                \
  X(LOAD_CONST_IMMORTAL)                       \
  X(LOAD_CONST_MORTAL)                         \
  X(LOAD_FIELD)                                \
  X(LOAD_FROM_DICT_OR_DEREF)                   \
  X(LOAD_FROM_DICT_OR_GLOBALS)                 \
  X(LOAD_ITERABLE_ARG)                         \
  X(LOAD_LOCAL)                                \
  X(LOAD_LOCALS)                               \
  X(LOAD_MAPPING_ARG)                          \
  X(LOAD_METHOD_STATIC)                        \
  X(LOAD_METHOD_STATIC_CACHED)                 \
  X(LOAD_OBJ_FIELD)                            \
  X(LOAD_PRIMITIVE_FIELD)                      \
  X(LOAD_SUPER_ATTR_ATTR)                      \
  X(LOAD_SUPER_ATTR_METHOD)                    \
  X(LOAD_TYPE)                                 \
  X(POP_JUMP_IF_NONZERO)                       \
  X(POP_JUMP_IF_ZERO)                          \
  X(PRIMITIVE_BINARY_OP)                       \
  X(PRIMITIVE_BOX)                             \
  X(PRIMITIVE_COMPARE_OP)                      \
  X(PRIMITIVE_LOAD_CONST)                      \
  X(PRIMITIVE_UNARY_OP)                        \
  X(PRIMITIVE_UNBOX)                           \
  X(REFINE_TYPE)                               \
  X(RESERVED)                                  \
  X(RESUME_CHECK)                              \
  X(RETURN_PRIMITIVE)                          \
  X(SEND_GEN)                                  \
  X(SEQUENCE_GET)                              \
  X(SEQUENCE_SET)                              \
  X(SETUP_CLEANUP)                             \
  X(STORE_FAST_MAYBE_NULL)                     \
  X(STORE_FIELD)                               \
  X(STORE_LOCAL)                               \
  X(STORE_LOCAL_CACHED)                        \
  X(STORE_OBJ_FIELD)                           \
  X(STORE_PRIMITIVE_FIELD)                     \
  X(TO_BOOL_ALWAYS_TRUE)                       \
  X(TO_BOOL_BOOL)                              \
  X(TO_BOOL_INT)                               \
  X(TO_BOOL_LIST)                              \
  X(TO_BOOL_NONE)                              \
  X(TO_BOOL_STR)                               \
  X(TP_ALLOC)                                  \
  X(TP_ALLOC_CACHED)

#elif PY_VERSION_HEX < 0x030E0000

#define STUB_OPCODE_DEFS(X)            \
  X(BINARY_ADD)                        \
  X(BINARY_AND)                        \
  X(BINARY_FLOOR_DIVIDE)               \
  X(BINARY_LSHIFT)                     \
  X(BINARY_MATRIX_MULTIPLY)            \
  X(BINARY_MODULO)                     \
  X(BINARY_MULTIPLY)                   \
  X(BINARY_OR)                         \
  X(BINARY_POWER)                      \
  X(BINARY_RSHIFT)                     \
  X(BINARY_SUBSCR_DICT_STR)            \
  X(BINARY_SUBSCR_LIST)                \
  X(BINARY_SUBSCR_TUPLE)               \
  X(BINARY_SUBSCR_TUPLE_CONST_INT)     \
  X(BINARY_OP_SUBSCR_LIST_INT)         \
  X(BINARY_OP_SUBSCR_TUPLE_INT)        \
  X(BINARY_OP_SUBSCR_DICT)             \
  X(BINARY_SUBTRACT)                   \
  X(BINARY_TRUE_DIVIDE)                \
  X(BINARY_XOR)                        \
  X(BUILD_INTERPOLATION)               \
  X(BUILD_TEMPLATE)                    \
  X(CALL_FUNCTION)                     \
  X(CALL_FUNCTION_KW)                  \
  X(CALL_KW)                           \
  X(CALL_METHOD)                       \
  X(CONVERT_VALUE)                     \
  X(COPY_DICT_WITHOUT_KEYS)            \
  X(DUP_TOP)                           \
  X(DUP_TOP_TWO)                       \
  X(FORMAT_WITH_SPEC)                  \
  X(FORMAT_SIMPLE)                     \
  X(EXTENDED_OPCODE)                   \
  X(GEN_START)                         \
  X(INPLACE_ADD)                       \
  X(INPLACE_AND)                       \
  X(INPLACE_FLOOR_DIVIDE)              \
  X(INPLACE_LSHIFT)                    \
  X(INPLACE_MATRIX_MULTIPLY)           \
  X(INPLACE_MODULO)                    \
  X(INPLACE_MULTIPLY)                  \
  X(INPLACE_OR)                        \
  X(INPLACE_POWER)                     \
  X(INPLACE_RSHIFT)                    \
  X(INPLACE_SUBTRACT)                  \
  X(INPLACE_TRUE_DIVIDE)               \
  X(INPLACE_XOR)                       \
  X(JUMP_ABSOLUTE)                     \
  X(JUMP_IF_FALSE_OR_POP)              \
  X(JUMP_IF_NOT_EXC_MATCH)             \
  X(JUMP_IF_TRUE_OR_POP)               \
  X(LIST_TO_TUPLE)                     \
  X(LOAD_ATTR_DICT_DESCR)              \
  X(LOAD_ATTR_DICT_NO_DESCR)           \
  X(LOAD_ATTR_NO_DICT_DESCR)           \
  X(LOAD_ATTR_POLYMORPHIC)             \
  X(LOAD_ATTR_SPLIT_DICT)              \
  X(LOAD_ATTR_SPLIT_DICT_DESCR)        \
  X(LOAD_ATTR_SUPER)                   \
  X(LOAD_ATTR_S_MODULE)                \
  X(LOAD_ATTR_TYPE)                    \
  X(LOAD_ATTR_UNCACHABLE)              \
  X(LOAD_COMMON_CONSTANT)              \
  X(LOAD_FAST_BORROW)                  \
  X(LOAD_FAST_BORROW_LOAD_FAST_BORROW) \
  X(LOAD_FAST_LOAD_FAST)               \
  X(LOAD_METHOD_DICT_DESCR)            \
  X(LOAD_METHOD_DICT_METHOD)           \
  X(LOAD_METHOD_MODULE)                \
  X(LOAD_METHOD_NO_DICT_DESCR)         \
  X(LOAD_METHOD_NO_DICT_METHOD)        \
  X(LOAD_METHOD_SPLIT_DICT_DESCR)      \
  X(LOAD_METHOD_SPLIT_DICT_METHOD)     \
  X(LOAD_METHOD_SUPER)                 \
  X(LOAD_METHOD_S_MODULE)              \
  X(LOAD_METHOD_TYPE)                  \
  X(LOAD_METHOD_TYPE_METHODLIKE)       \
  X(LOAD_METHOD_UNCACHABLE)            \
  X(LOAD_METHOD_UNSHADOWED_METHOD)     \
  X(LOAD_SMALL_INT)                    \
  X(LOAD_SPECIAL)                      \
  X(MAKE_OPNAME)                       \
  X(NOT_TAKEN)                         \
  X(POP_ITER)                          \
  X(ROT_FOUR)                          \
  X(ROT_N)                             \
  X(ROT_THREE)                         \
  X(ROT_TWO)                           \
  X(SETUP_ASYNC_WITH)                  \
  X(STORE_ATTR_DESCR)                  \
  X(STORE_ATTR_DICT)                   \
  X(STORE_ATTR_SPLIT_DICT)             \
  X(SET_FUNCTION_ATTRIBUTE)            \
  X(STORE_ATTR_UNCACHABLE)             \
  X(STORE_FAST_STORE_FAST)             \
  X(STORE_FAST_LOAD_FAST)              \
  X(TO_BOOL)                           \
  X(UNARY_POSITIVE)                    \
  X(YIELD_FROM)

#elif PY_VERSION_HEX < 0x030F0000

#define STUB_OPCODE_DEFS(X)        \
  X(BEFORE_ASYNC_WITH)             \
  X(BEFORE_WITH)                   \
  X(BINARY_ADD)                    \
  X(BINARY_AND)                    \
  X(BINARY_FLOOR_DIVIDE)           \
  X(BINARY_LSHIFT)                 \
  X(BINARY_MATRIX_MULTIPLY)        \
  X(BINARY_MODULO)                 \
  X(BINARY_MULTIPLY)               \
  X(BINARY_OR)                     \
  X(BINARY_POWER)                  \
  X(BINARY_RSHIFT)                 \
  X(BINARY_SUBSCR)                 \
  X(BINARY_SUBSCR_DICT_STR)        \
  X(BINARY_SUBSCR_LIST)            \
  X(BINARY_SUBSCR_TUPLE)           \
  X(BINARY_SUBSCR_TUPLE_CONST_INT) \
  X(BINARY_SUBSCR_TUPLE_INT)       \
  X(BINARY_SUBSCR_LIST_INT)        \
  X(BINARY_SUBSCR_DICT)            \
  X(BINARY_SUBTRACT)               \
  X(BINARY_TRUE_DIVIDE)            \
  X(BINARY_XOR)                    \
  X(BUILD_CONST_KEY_MAP)           \
  X(CALL_FUNCTION)                 \
  X(CALL_FUNCTION_KW)              \
  X(CALL_METHOD)                   \
  X(COPY_DICT_WITHOUT_KEYS)        \
  X(DUP_TOP)                       \
  X(DUP_TOP_TWO)                   \
  X(FORMAT_VALUE)                  \
  X(GEN_START)                     \
  X(INPLACE_ADD)                   \
  X(INPLACE_AND)                   \
  X(INPLACE_FLOOR_DIVIDE)          \
  X(INPLACE_LSHIFT)                \
  X(INPLACE_MATRIX_MULTIPLY)       \
  X(INPLACE_MODULO)                \
  X(INPLACE_MULTIPLY)              \
  X(INPLACE_OR)                    \
  X(INPLACE_POWER)                 \
  X(INPLACE_RSHIFT)                \
  X(INPLACE_SUBTRACT)              \
  X(INPLACE_TRUE_DIVIDE)           \
  X(INPLACE_XOR)                   \
  X(JUMP_ABSOLUTE)                 \
  X(JUMP_IF_FALSE_OR_POP)          \
  X(JUMP_IF_NOT_EXC_MATCH)         \
  X(JUMP_IF_NONZERO_OR_POP)        \
  X(JUMP_IF_TRUE_OR_POP)           \
  X(JUMP_IF_ZERO_OR_POP)           \
  X(KW_NAMES)                      \
  X(LIST_TO_TUPLE)                 \
  X(LOAD_ASSERTION_ERROR)          \
  X(LOAD_ATTR_DICT_DESCR)          \
  X(LOAD_ATTR_DICT_NO_DESCR)       \
  X(LOAD_ATTR_NO_DICT_DESCR)       \
  X(LOAD_ATTR_POLYMORPHIC)         \
  X(LOAD_ATTR_SPLIT_DICT)          \
  X(LOAD_ATTR_SPLIT_DICT_DESCR)    \
  X(LOAD_ATTR_SUPER)               \
  X(LOAD_ATTR_S_MODULE)            \
  X(LOAD_ATTR_TYPE)                \
  X(LOAD_ATTR_UNCACHABLE)          \
  X(LOAD_METHOD)                   \
  X(LOAD_METHOD_DICT_DESCR)        \
  X(LOAD_METHOD_DICT_METHOD)       \
  X(LOAD_METHOD_MODULE)            \
  X(LOAD_METHOD_NO_DICT_DESCR)     \
  X(LOAD_METHOD_NO_DICT_METHOD)    \
  X(LOAD_METHOD_SPLIT_DICT_DESCR)  \
  X(LOAD_METHOD_SPLIT_DICT_METHOD) \
  X(LOAD_METHOD_SUPER)             \
  X(LOAD_METHOD_S_MODULE)          \
  X(LOAD_METHOD_TYPE)              \
  X(LOAD_METHOD_TYPE_METHODLIKE)   \
  X(LOAD_METHOD_UNCACHABLE)        \
  X(LOAD_METHOD_UNSHADOWED_METHOD) \
  X(MAKE_OPNAME)                   \
  X(RETURN_CONST)                  \
  X(ROT_FOUR)                      \
  X(ROT_N)                         \
  X(ROT_THREE)                     \
  X(ROT_TWO)                       \
  X(SETUP_ASYNC_WITH)              \
  X(STORE_ATTR_DESCR)              \
  X(STORE_ATTR_DICT)               \
  X(STORE_ATTR_SPLIT_DICT)         \
  X(STORE_ATTR_UNCACHABLE)         \
  X(UNARY_POSITIVE)                \
  X(YIELD_FROM)

#else

#define STUB_OPCODE_DEFS(X)        \
  X(BEFORE_ASYNC_WITH)             \
  X(BEFORE_WITH)                   \
  X(BINARY_ADD)                    \
  X(BINARY_AND)                    \
  X(BINARY_FLOOR_DIVIDE)           \
  X(BINARY_LSHIFT)                 \
  X(BINARY_MATRIX_MULTIPLY)        \
  X(BINARY_MODULO)                 \
  X(BINARY_MULTIPLY)               \
  X(BINARY_OR)                     \
  X(BINARY_POWER)                  \
  X(BINARY_RSHIFT)                 \
  X(BINARY_SUBSCR)                 \
  X(BINARY_SUBSCR_DICT_STR)        \
  X(BINARY_SUBSCR_LIST)            \
  X(BINARY_SUBSCR_TUPLE)           \
  X(BINARY_SUBSCR_TUPLE_CONST_INT) \
  X(BINARY_SUBSCR_TUPLE_INT)       \
  X(BINARY_SUBSCR_LIST_INT)        \
  X(BINARY_SUBSCR_DICT)            \
  X(BINARY_SUBTRACT)               \
  X(BINARY_TRUE_DIVIDE)            \
  X(BINARY_XOR)                    \
  X(BUILD_CONST_KEY_MAP)           \
  X(CALL_FUNCTION)                 \
  X(CALL_FUNCTION_KW)              \
  X(CALL_METHOD)                   \
  X(COPY_DICT_WITHOUT_KEYS)        \
  X(DUP_TOP)                       \
  X(DUP_TOP_TWO)                   \
  X(FORMAT_VALUE)                  \
  X(GEN_START)                     \
  X(GET_YIELD_FROM_ITER)           \
  X(INPLACE_ADD)                   \
  X(INPLACE_AND)                   \
  X(INPLACE_FLOOR_DIVIDE)          \
  X(INPLACE_LSHIFT)                \
  X(INPLACE_MATRIX_MULTIPLY)       \
  X(INPLACE_MODULO)                \
  X(INPLACE_MULTIPLY)              \
  X(INPLACE_OR)                    \
  X(INPLACE_POWER)                 \
  X(INPLACE_RSHIFT)                \
  X(INPLACE_SUBTRACT)              \
  X(INPLACE_TRUE_DIVIDE)           \
  X(INPLACE_XOR)                   \
  X(JUMP_ABSOLUTE)                 \
  X(JUMP_IF_FALSE_OR_POP)          \
  X(JUMP_IF_NOT_EXC_MATCH)         \
  X(JUMP_IF_NONZERO_OR_POP)        \
  X(JUMP_IF_TRUE_OR_POP)           \
  X(JUMP_IF_ZERO_OR_POP)           \
  X(KW_NAMES)                      \
  X(LIST_TO_TUPLE)                 \
  X(LOAD_ASSERTION_ERROR)          \
  X(LOAD_ATTR_DICT_DESCR)          \
  X(LOAD_ATTR_DICT_NO_DESCR)       \
  X(LOAD_ATTR_NO_DICT_DESCR)       \
  X(LOAD_ATTR_POLYMORPHIC)         \
  X(LOAD_ATTR_SPLIT_DICT)          \
  X(LOAD_ATTR_SPLIT_DICT_DESCR)    \
  X(LOAD_ATTR_SUPER)               \
  X(LOAD_ATTR_S_MODULE)            \
  X(LOAD_ATTR_TYPE)                \
  X(LOAD_ATTR_UNCACHABLE)          \
  X(LOAD_METHOD)                   \
  X(LOAD_METHOD_DICT_DESCR)        \
  X(LOAD_METHOD_DICT_METHOD)       \
  X(LOAD_METHOD_MODULE)            \
  X(LOAD_METHOD_NO_DICT_DESCR)     \
  X(LOAD_METHOD_NO_DICT_METHOD)    \
  X(LOAD_METHOD_SPLIT_DICT_DESCR)  \
  X(LOAD_METHOD_SPLIT_DICT_METHOD) \
  X(LOAD_METHOD_SUPER)             \
  X(LOAD_METHOD_S_MODULE)          \
  X(LOAD_METHOD_TYPE)              \
  X(LOAD_METHOD_TYPE_METHODLIKE)   \
  X(LOAD_METHOD_UNCACHABLE)        \
  X(LOAD_METHOD_UNSHADOWED_METHOD) \
  X(MAKE_OPNAME)                   \
  X(RETURN_CONST)                  \
  X(ROT_FOUR)                      \
  X(ROT_N)                         \
  X(ROT_THREE)                     \
  X(ROT_TWO)                       \
  X(SETUP_ASYNC_WITH)              \
  X(STORE_ATTR_DESCR)              \
  X(STORE_ATTR_DICT)               \
  X(STORE_ATTR_SPLIT_DICT)         \
  X(STORE_ATTR_UNCACHABLE)         \
  X(UNARY_POSITIVE)                \
  X(YIELD_FROM)

#endif

enum {
  // Uses magic value to put these in a completely bogus range that doesn't fit
  // in one byte.  Fits in two bytes which matches how CPython handles pseudo
  // opcodes.
  STUB_OPCODE_BEGIN = 40000,
#define DEFINE_OPCODE(NAME) NAME,
  STUB_OPCODE_DEFS(DEFINE_OPCODE)
#undef DEFINE_OPCODE
};
